# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize <- function(x, y, nnn = "sqrtn") {
    .Call(`_CDJNC_normalize`, x, y, nnn)
}

gdata <- function(n = 200L, p = 1000L, K = 10L, sigma = 0.1, ratio = 1.0, kind = 1L, rho = 1.0e-10, seed = 1L, isnorm = TRUE, nnn = "sqrtn", snr = 1.0e-10) {
    .Call(`_CDJNC_gdata`, n, p, K, sigma, ratio, kind, rho, seed, isnorm, nnn, snr)
}

soft <- function(z, lambda = 1) {
    .Call(`_CDJNC_soft`, z, lambda)
}

thresh <- function(z, lambda = 1, gamma = 3, pen = "mcp") {
    .Call(`_CDJNC_thresh`, z, lambda, gamma, pen)
}

cdj <- function(x, y, beta0, pen = "mcp", nnn = "sqrtn", la = 1.0, ga = 3.0, mu = 0.5, imax = 5L, tol = 1.0e-5) {
    .Call(`_CDJNC_cdj`, x, y, beta0, pen, nnn, la, ga, mu, imax, tol)
}

lamfun <- function(x, y, N = 100L, pen = "mcp", nnn = "sqrtn", Lmin = 1.0e-10, tau = 0.5) {
    .Call(`_CDJNC_lamfun`, x, y, N, pen, nnn, Lmin, tau)
}

tune_cdj <- function(x, y, pen = "mcp", nnn = "sqrtn", N = 100L, Lmin = 1.0e-5, ga = 1.0e-10, mu = 0.5, imax = 1L, tol = 1.0e-5) {
    .Call(`_CDJNC_tune_cdj`, x, y, pen, nnn, N, Lmin, ga, mu, imax, tol)
}

